# Generated by Django 5.2.3 on 2025-07-01 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="bestämt_plural_correct",
            new_name="bestamt_plural_correct",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="bestämt_plural_incorrect",
            new_name="bestamt_plural_incorrect",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="bestämt_singular_correct",
            new_name="bestamt_singular_correct",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="bestämt_singular_incorrect",
            new_name="bestamt_singular_incorrect",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="obestämt_plural_correct",
            new_name="obestamt_plural_correct",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="obestämt_plural_incorrect",
            new_name="obestamt_plural_incorrect",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="obestämt_singular_correct",
            new_name="obestamt_singular_correct",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="obestämt_singular_incorrect",
            new_name="obestamt_singular_incorrect",
        ),
    ]
