# Generated by Django 5.2.3 on 2025-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_rename_bestämt_plural_correct_customuser_bestamt_plural_correct_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_substantiv_answered",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_verb_answered",
            field=models.IntegerField(default=0),
        ),
    ]
