# Generated by Django 5.2 on 2025-08-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_imperativ_correct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='infinitv_correct',
            new_name='infinitiv_correct',
        ),
    ]
