# Generated by Django 5.2.3 on 2025-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("svenska", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Substantiv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("category", models.CharField()),
                ("ord", models.CharField()),
                ("engelska", models.CharField()),
                ("obestämt_singular", models.CharField()),
                ("bestämt_singular", models.CharField()),
                ("obestämt_plural", models.CharField()),
                ("betsämt_plural", models.CharField()),
            ],
        ),
    ]
