# Generated by Django 5.2.3 on 2025-06-30 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("svenska", "0002_substantiv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="substantiv",
            old_name="betsämt_plural",
            new_name="betstämt_plural",
        ),
    ]
