# Generated by Django 5.2.3 on 2025-06-30 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("svenska", "0003_rename_betsämt_plural_substantiv_betstämt_plural"),
    ]

    operations = [
        migrations.RenameField(
            model_name="substantiv",
            old_name="betstämt_plural",
            new_name="bestämt_plural",
        ),
    ]
