# Generated by Django 5.2.3 on 2025-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("svenska", "0004_rename_betstämt_plural_substantiv_bestämt_plural"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("ord", models.CharField()),
                ("engelska", models.CharField()),
                ("infinitiv", models.CharField()),
                ("presens", models.CharField()),
                ("imperativ", models.CharField()),
                ("preteritum", models.CharField()),
                ("perfekt", models.CharField()),
                ("pluskvamperfekt", models.CharField()),
            ],
        ),
    ]
