# Generated by Django 5.2 on 2025-08-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svenska', '0005_verb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substantiv',
            old_name='bestämt_plural',
            new_name='bestamt_plural',
        ),
        migrations.RenameField(
            model_name='substantiv',
            old_name='bestämt_singular',
            new_name='bestamt_singular',
        ),
        migrations.RenameField(
            model_name='substantiv',
            old_name='obestämt_plural',
            new_name='obestamt_plural',
        ),
        migrations.RenameField(
            model_name='substantiv',
            old_name='obestämt_singular',
            new_name='obestamt_singular',
        ),
    ]
